### ISSUE TITLE
Many URL status "403" in Easter Island are not 403

### ISSUE THREAD

**Issue by greencardamom** [internetarchive/ware#6] opened 2023-03-22 19:49 UTC
Example https://www.sciencedaily.com/releases/2021/07/210713090153.htm is 202 and https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2042672 is 200

**Comment by mojomonger** [comment] 2023-03-22 23:46
accoding to https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

> The HTTP 403 Forbidden response status code indicates that the server understands the request but refuses to authorize it.

> This status is similar to 401, but for the 403 Forbidden status code, re-authenticating makes no difference. The access is tied to the application logic, such as insufficient rights to a resource.

it seems that it may have something to do with permission rights from the wari servers?

**Comment by geohci** [comment] 2023-03-23 16:47
I've run into this issue on related projects and it was helped there by setting a user-agent when requesting the page content if you haven't. Example: https://github.com/geohci/side/blob/main/verify_wikipedia/passages/web_source.py#L16

**Comment by dpriskorn** [comment] 2023-03-23 18:12
Hi, thanks for the report. Using curl I get:
![image](https://user-images.githubusercontent.com/68460690/227305993-338a1562-e4ea-48d7-beba-67b47db58672.png)
So the response code is correct. 
We currently only show what the web servers first response is. Most 403s lead to 200s from what I have seen.

**Comment by dpriskorn** [comment] 2023-03-23 18:13
closing this as it is expected behavior and thus not a bug

**Closed by dpriskorn** 2023-03-23 18:13 UTC
Labels: bug

**Comment by greencardamom** [comment] 2023-03-23 18:22
403 is not normal. Curl out of the box without options is not optimized for general web page retrieval and can give strange results. Try with wget which is optimized for general web page retrieval and it returns 200 is the correct status code. Let me know if you want the wget command for header retrieval.

**Comment by greencardamom** [comment] 2023-03-23 18:26
The problem with curl is a missing agent string. Try adding -A "MyAgent" and it will return 200.

**Comment by dpriskorn** [comment] 2023-03-29 09:05
Fixed in the backend by adding a ton of spoofed headers similar to what browsers do, see the issue referenced above.
